version: "3"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.32
    ports:
      - "16686:16686"
      - "5775:5775/udp" 
      - "6831:6831/udp" 
      - "6832:6832/udp" 
      - "5778:5778" 
      - "14250:14250" 
      - "14268:14268" 
      - "14269:14269" 
      - "9411:9411"
    environment:
    - COLLECTOR_ZIPKIN_HOST_PORT=:9411      
  krakend_ce:
    image: devopsfaith/krakend:latest
    volumes:
      - .:/etc/krakend
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
    depends_on:
      - jaeger